### ISSUE TITLE
XOR

### ISSUE THREAD

**Issue by januszjasinski** [N-2-O/DiceCTF2022#1]
How did you know to XOR those characters? Seems a bit random. How did you know to XOR those specific ones?

**Comment by N-2-O** [comment]
> How did you know to XOR those characters? Seems a bit random. How did you know to XOR those specific ones?

In the DG4-A document, we're actually given the key and the ciphertext. To find the plaintext, we simply XOR the two we know. Hope this helps :)

**Comment by januszjasinski** [comment]
Are we? Where? How did you specifically know to xor those values. There are loads of integers but how did you know which ones to xor? Looking at your script it looks as though you did it randomly and just happen to picked the right ones
